# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--requirepass mypassword
    restart: unless-stopped
    
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379:0:mypassword
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data: